// Generated by alg3
`timescale 1ns/10ps
typedef struct packed {
  reg [6:0] funct7;
  reg [4:0] rs2;
  reg [4:0] rs1;
  reg [2:0] funct3;
  reg [4:0] rd;
  reg [4:0] opcode5;
  reg [1:0] ones;
} Rtype_ref;
typedef struct packed {
  reg [11:0] imm12;
  reg [4:0] rs1;
  reg [2:0] funct3;
  reg [4:0] rd;
  reg [4:0] opcode5;
  reg [1:0] ones;
} Itype_ref;
typedef struct packed {
  reg [6:0] imm11_5;
  reg [4:0] rs2;
  reg [4:0] rs1;
  reg [2:0] funct3;
  reg [4:0] imm4_0;
  reg [4:0] opcode5;
  reg [1:0] ones;
} Stype_ref;
typedef struct packed {
  reg [6:0] imm12_10_5;
  reg [4:0] rs2;
  reg [4:0] rs1;
  reg [2:0] funct3;
  reg [4:0] imm4_1_11;
  reg [4:0] opcode5;
  reg [1:0] ones;
} Btype_ref;
typedef struct packed {
  reg [19:0] imm31_12;
  reg [4:0] rd;
  reg [4:0] opcode5;
  reg [1:0] ones;
} Utype_ref;
typedef struct packed {
  reg [19:0] imm20_10_1_11_19_12;
  reg [4:0] rd;
  reg [4:0] opcode5;
  reg [1:0] ones;
} Jtype_ref;
typedef union packed {
  Rtype_ref R;
  Itype_ref I;
  Stype_ref S;
  Btype_ref B;
  Utype_ref U;
  Jtype_ref J;
  reg [31:0] raw;
 } iunion_ref;
